apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-redis
  namespace: default
spec:
  selector:
    matchLabels:
      app: ktor-redis
  template:
    metadata:
      labels:
        app: ktor-redis
    spec:
      containers:
      - image: mimikko/ktor-redis:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: ktor-redis
        env:
        - name: branch
          value: <BRANCH_NAME>
